server:
  port: 8888
  address: 0.0.0.0

elasticsearch:
  host: 172.30.1.81
  port: 9200

datasource:
  url: jdbc:mysql://localhost:3306/glue?characterEncoding=UTF-8&serverTimezone=UTC&
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root